-- Файл создаётся автоматически панелью настроек пилюли (Super+I).
-- Правки руками будут затёрты при следующей смене сочетания.
return {
    ["browser"] = "",
    ["closeWindow"] = "SUPER + Q",
    ["emptyWorkspace"] = "SUPER + Space",
    ["exitHypr"] = "SUPER + SHIFT + M",
    ["fileManager"] = "SUPER + E",
    ["fileManagerTui"] = "SUPER + SHIFT + E",
    ["floatCenter"] = "SUPER + SHIFT + Space",
    ["floatToggle"] = "",
    ["fullscreen"] = "SUPER + SHIFT + F",
    ["notes"] = "SUPER + O",
    ["overview"] = "SUPER + Tab",
    ["packWorkspaces"] = "SUPER + SHIFT + A",
    ["pillBt"] = "SUPER + SHIFT + B",
    ["pillClip"] = "SUPER + V",
    ["pillControls"] = "SUPER + Z",
    ["pillLauncher"] = "SUPER + F",
    ["pillNotif"] = "SUPER + SHIFT + N",
    ["pillPower"] = "CTRL + ALT + delete",
    ["pillRecord"] = "SUPER + P",
    ["pillSettings"] = "SUPER + I",
    ["pillShortcuts"] = "SUPER + M",
    ["pillVault"] = "SUPER + SHIFT + P",
    ["pillWifi"] = "SUPER + SHIFT + W",
    ["screenOff"] = "SUPER + SHIFT + F12",
    ["screenshot"] = "SUPER + SHIFT + S",
    ["specialWorkspace"] = "",
    ["terminal"] = "SUPER + T",
    ["terminalAlt"] = "SUPER + Return",
    ["themeSwitch"] = "SUPER + SHIFT + T",
    ["toggleSplit"] = "SUPER + J",
    ["voxDictate"] = "Alt_R",
}
