// Generated by panacea/scripts/vibrance.sh -- edits will be overwritten.
#version 300 es
precision highp float;
in vec2 v_texcoord;
uniform sampler2D tex;
out vec4 fragColor;

const float STRENGTH = 0.2000;

void main() {
    vec4 px = texture(tex, v_texcoord);

    float lum = dot(px.rgb, vec3(0.2126, 0.7152, 0.0722));

    float mx  = max(px.r, max(px.g, px.b));
    float mn  = min(px.r, min(px.g, px.b));
    float sat = mx - mn;

    float weight = STRENGTH > 0.0 ? (1.0 - sat) : 1.0;
    float amount = STRENGTH * weight;
    vec3 outRgb = mix(vec3(lum), px.rgb, 1.0 + amount);

    fragColor = vec4(clamp(outRgb, 0.0, 1.0), px.a);
}
